### ISSUE TITLE
Low frame rate and low GPU occupancy rate

### ISSUE THREAD

**Issue by JadyXuan** [pkhungurn/talking-head-anime-demo#10]
The torch.cuda.is_available() print out True, and the dlib also use gpu (dlib.DLIIB_USE_CUDA() is True)
However when the script runs it occupies 20% CPU and only 0.5% GPU
![TIM图片20200217153328](https://user-images.githubusercontent.com/35390572/74632971-8e747900-519b-11ea-8721-135b43ab0569.png)
And the frame rate only 4 fps
I wonder if it is other step that slow the frames output rate?How can I accelerate it><

**Comment by dragonmeteor** [comment]
Thank you for the information. The answer is: I don't know. Maybe you can find out and tell me. :)

**Comment by dragonmeteor** [comment]
A theory is that the Windows Task Manager might not be the best tool to measure how much your GPU is used. Use Open Hardware Monitor (https://openhardwaremonitor.org/) instead and you might see a different number.

When I used the Puppeteer tool, Windows Task Manager showed that only 0.4% of the GPU was used by the Python process. On the other hand, Open Hardware Monitor showed that 39% of the GPU was used instead of just 0.5%

![gpu-usage](https://user-images.githubusercontent.com/244849/74667905-8510fe00-51e7-11ea-8285-ad9d03d9be6b.png)

**Comment by JadyXuan** [comment]
![BN4SL23YDZ2ZHSIIV4OU__G](https://user-images.githubusercontent.com/35390572/74719707-871e9f80-526f-11ea-9f5f-2a8a46fe9694.png)
That' true,  it's my GPU that can't run faster. I think it's time to get a more expensive GPU. xwx
