### ISSUE TITLE
Manual poser, "Nothing yet!"

### ISSUE THREAD

**Issue by Ceiru** [pkhungurn/talking-head-anime-demo#16]
Have opened the program, loaded the sample image, but the right screen keeps saying "Nothing yet!", was there anything i missed?

**Comment by dragonmeteor** [comment]
Is there any error messages printed on the console?

**Comment by zyasu** [comment]
I have similar problem, too.
error messages are
File "talking-head-anime-demo-master/tha/two_algo_face_rotator.py", line 56, in forward
    base_grid = affine_grid(identity, [n, c, h, w], align_corners=self.align_corners)
TypeError: affine_grid() got an unexpected keyword argument 'align_corners'

please tell me solutions.

**Comment by dragonmeteor** [comment]
Please update your PyTorch installation to be at least version 1.3. The align_corners option was introduced in that version.

**Comment by philipwelia** [comment]
> Please update your PyTorch installation to be at least version 1.3. The align_corners option was introduced in that version.

I meet similar issue with the  version 1.4.0.
there aren't any images showed on the screen or any error massages on the console

**Comment by dragonmeteor** [comment]
It is impossible to find out what's wrong without seeing what the errors look like. If there's nothing showing out, please take a screenshot or a video of your screen, *including* the command prompt that you invoked the program with.

**Comment by huan-end** [comment]
In the 'app', manual_poser.py,when i am running the program, ”Module 'typing' has no attribute 'ForwardRef' error “and show the "from poser.morph_rotate_combine_poser import MorphRotateCombinePoser256Param6"has a promble,how to deal with it?Is it a Python package?

**Comment by huan-end** [comment]
There has the same promble in 'app/puppeteer'.

**Comment by dragonmeteor** [comment]
I seems the problem is in your Python installation. The source code that is distributed in this repository does use the "typing" module, but it does not use any "ForwardRef." Your Python installation seems to have a problem when the "typing" module is used.

The easiest way to solve this is to try installing the code in a newly created Python environment. I have provided instruction to do it with Anaconda in the README file. Please try it.

**Comment by huan-end** [comment]
Thank you,the problem has already been settled.I&nbsp; deleted the package of 'poser',that's the reason.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pkhungurn/talking-head-anime-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 晚上11:25
收件人:&nbsp;"pkhungurn/talking-head-anime-demo"<talking-head-anime-demo@noreply.github.com&gt;;
抄送:&nbsp;"微生物"<2876256698@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [pkhungurn/talking-head-anime-demo] Manual poser, "Nothing yet!" (#16)





 
I seems the problem is in your Python installation. The source code that is distributed in this repository does use the "typing" module, but it does not use any "ForwardRef." Your Python installation seems to have a problem when the "typing" module is used.
 
The easiest way to solve this is to try installing the code in a newly created Python environment. I have provided instruction to do it with Anaconda in the README file. Please try it.
