### ISSUE TITLE
Shoulder Movements

### ISSUE THREAD

**Issue by t-qureshi** [pkhungurn/talking-head-anime-demo#21]
Hye ,@dragonmeteor @sheiun,
First of All thanks for this great work. Its results are really good. I just want to move the shoulder as well . Kindly guide me how i can achieve this thing.

**Comment by dragonmeteor** [comment]
If it were me, I would create a new model that takes a larger image contains the whole upper body. I would then generate a new dataset that contains upper body movement. (I'm not sure how to do this because I don't yet know how to control shoulders.) Then I would train the new model on the new dataset and iterate on the architecture.
